// <auto-generated> tools/bake_strings.py from docs/strings/*.json.
// Do not edit; regenerate. Authoring notes live in docs/I18N.md.
namespace GridInfect.Game
{
    public static partial class Str
    {
        public const string DefaultTag = "en";

        // Every shipped tag, default first. The selector draws this
        // list minus the pseudolocales (docs/I18N.md).
        public static readonly string[] Tags =
        {
            "en",
            "qps-ploc",
            "qps-plocm",
        };

        public static readonly bool[] IsPseudo =
        {
            false,
            true,
            true,
        };

        // en
        static readonly string[] En =
        {
            "MENU",   // nav.menu
            "WORLDS",   // nav.worlds
            "SETTINGS",   // nav.settings
            "{0}/{1}",   // common.page
            "WORLDS",   // menu.worlds
            "DAILY",   // menu.daily
            "ENDLESS",   // menu.endless
            "LEGACY",   // menu.legacy
            "TUTORIAL",   // menu.tutorial
            "NO ADS",   // menu.noAds
            "FIRST TIME?",   // menu.offer.title
            "Learn the basics in a minute.",   // menu.offer.line
            "TUTORIAL",   // menu.offer.accept
            "SKIP",   // menu.offer.skip
            "SETTINGS",   // settings.title
            "PRIVACY OPTIONS",   // settings.privacy
            "LANGUAGE",   // settings.language
            "ERASES EVERY LEVEL BEATEN\nAND EVERY SCORE. LOCKS ARE KEPT.",   // settings.eraseCaption
            "V{0}   BUILD {1}",   // settings.build
            "EDITOR",   // settings.buildEditor
            "SOUND: ON",   // settings.soundOn
            "SOUND: OFF",   // settings.soundOff
            "RESET PROGRESS",   // settings.reset
            "TAP AGAIN TO ERASE",   // settings.resetArmed
            "GREEN",   // settings.skin.green
            "BLUE",   // settings.skin.blue
            "TAN",   // settings.skin.tan
            "CLEAR\nALL WORLDS",   // settings.skin.wantWorlds
            "CLEAR\nALL LEGACY",   // settings.skin.wantLegacy
            "HOW TO PLAY",   // rules.title
            "Infect every cell on the board to win.",   // rules.goal
            "Drag a bug onto any cell.",   // rules.intro
            "A ray runs to the edge, over gaps.",   // rules.diagram
            "Win on a repel or trap and it still counts.",   // rules.note1
            "Hit an avoid cell and the drop bounces back.",   // rules.note2
            "Infect it.",   // rules.cell.infect
            "GAP",   // rules.cell.gap.name
            "Not a cell: rays cross it.",   // rules.cell.gap.line
            "WALL",   // rules.cell.wall.name
            "Blocks a ray.",   // rules.cell.wall.line
            "REPEL",   // rules.cell.repel.name
            "Clears back when hit.",   // rules.cell.repel.line
            "TRAP",   // rules.cell.trap.name
            "Clears the board when hit.",   // rules.cell.trap.line
            "RELAY",   // rules.cell.relay.name
            "Fires its own rays when hit.",   // rules.cell.relay.line
            "AVOID",   // rules.cell.avoid.name
            "Rays must not touch it.",   // rules.cell.avoid.line
            "Rays run to the edge.",   // rules.spread.cardinal
            "Or corner to corner.",   // rules.spread.diagonal
            "A blot takes the eight around it.",   // rules.spread.area
            "LEGACY",   // legacy.title
            "FREE PLAY",   // freeplay.title
            "BEGINNER",   // freeplay.difficulty.beginner
            "EASY",   // freeplay.difficulty.easy
            "MEDIUM",   // freeplay.difficulty.medium
            "HARD",   // freeplay.difficulty.hard
            "CHALLENGING",   // freeplay.difficulty.challenging
            "WORLDS",   // worlds.title
            "{0}  {1}",   // worlds.row
            "{0}/{1}",   // worlds.progress
            "DAILY",   // daily.title
            "TODAY",   // daily.today
            "PAST",   // daily.past
            "STREAK {0:00}",   // daily.streak
            "{0} {1:00}/{2:00}",   // daily.monthCount
            "{0} {1:00} {2}",   // daily.dateLine
            "BUGS {0}",   // daily.bugs
            "CELLS {0}",   // daily.cells
            "COMPLETE",   // daily.complete
            "GENERATING",   // daily.generating
            "UNPLAYED",   // daily.unplayed
            "PLAY AGAIN",   // daily.playAgain
            "BEGIN",   // daily.begin
            "ENDLESS",   // endless.title
            "BEST {0}",   // endless.best
            "RESET",   // board.reset
            "LEGACY",   // board.legacy
            "DAILY",   // board.daily
            "ENDLESS  {0}",   // board.endless
            "LEVEL {0}",   // board.level
            "TUTORIAL {0}/{1}",   // board.tutorialTitle
            "BEGIN",   // board.begin
            "HINT",   // board.hint
            "+1 SOLVE",   // board.plusSolve
            "SOLVE {0:00}",   // board.solve
            "COMPLETE",   // board.complete
            "COMPLETE\nStreak started",   // board.completeStreakStarted
            "COMPLETE\n{0} days in a row",   // board.completeStreakDays
            "TUTORIAL COMPLETE",   // board.tutorialComplete
            "MENU",   // board.popup.menu
            "REPLAY",   // board.popup.replay
            "NEXT",   // board.popup.next
            "PLAY",   // board.popup.play
            "CALENDAR",   // board.popup.calendar
            "SOLVED {0}",   // board.hud.solved
            "STREAK {0}",   // board.hud.streak
            "BEST {0}",   // board.hud.best
            "{0}/5",   // board.hud.runCount
            "TIER {0}",   // tier.name
            "T{0}",   // tier.short
            "{0}-{1}",   // tier.band
            "LOADING",   // loading.caption
            "LANGUAGE",   // language.title
            "AUTO",   // language.auto
            "MON",   // cal.day.1
            "TUE",   // cal.day.2
            "WED",   // cal.day.3
            "THU",   // cal.day.4
            "FRI",   // cal.day.5
            "SAT",   // cal.day.6
            "SUN",   // cal.day.7
            "JANUARY",   // cal.month.1
            "FEBRUARY",   // cal.month.2
            "MARCH",   // cal.month.3
            "APRIL",   // cal.month.4
            "MAY",   // cal.month.5
            "JUNE",   // cal.month.6
            "JULY",   // cal.month.7
            "AUGUST",   // cal.month.8
            "SEPTEMBER",   // cal.month.9
            "OCTOBER",   // cal.month.10
            "NOVEMBER",   // cal.month.11
            "DECEMBER",   // cal.month.12
            "JAN",   // cal.month.1.short
            "FEB",   // cal.month.2.short
            "MAR",   // cal.month.3.short
            "APR",   // cal.month.4.short
            "MAY",   // cal.month.5.short
            "JUN",   // cal.month.6.short
            "JUL",   // cal.month.7.short
            "AUG",   // cal.month.8.short
            "SEP",   // cal.month.9.short
            "OCT",   // cal.month.10.short
            "NOV",   // cal.month.11.short
            "DEC",   // cal.month.12.short
            "Drag the bug onto the marked cell.",   // tut.1.line
            "Rays cross gaps.",   // tut.2.line
            "Two bugs. Tap a placed bug to pick it up.",   // tut.3.line
            "A wall stops a ray.",   // tut.4.line
            "Bugs can also be diagonal.",   // tut.5.line
            "A blot takes the eight cells around it.",   // tut.6.line
            "A ray may never touch an avoid cell.",   // tut.7.line
            "A repel clears the ray that hit it.",   // tut.8.line
            "A trap resets the whole board.",   // tut.9.line
            "A relay fires its own rays when lit.",   // tut.10.line
            "FIRST STEPS",   // world.w01.name
            "TWO LINES",   // world.w02.name
            "CORNERS",   // world.w03.name
            "CROSSINGS",   // world.w04.name
            "KEEP CLEAN",   // world.w05.name
            "COUNTING",   // world.w06.name
            "CORRIDORS",   // world.w07.name
            "BLOTS",   // world.w08.name
            "LONG REACH",   // world.w09.name
            "FOUR ARMS",   // world.w10.name
            "DIAGONALS",   // world.w11.name
            "TIGHT",   // world.w12.name
            "RELAYS",   // world.w14.name
            "CROSSTALK",   // world.w15.name
            "SUPPOSE",   // world.w16.name
            "MASTERY",   // world.w17.name
        };

        // qps-ploc
        static readonly string[] QpsPloc =
        {
            "[M\u00c9\u00d1\u00da\u00b7\u00b7]",   // nav.menu
            "[W\u00d3RL\u0110\u0160\u00b7\u00b7]",   // nav.worlds
            "[\u0160\u00c9TT\u00cd\u00d1\u011e\u0160\u00b7\u00b7\u00b7]",   // nav.settings
            "[{0}/{1}]",   // common.page
            "[W\u00d3RL\u0110\u0160\u00b7\u00b7]",   // menu.worlds
            "[\u0110\u00c1\u00cdL\u00dd\u00b7\u00b7]",   // menu.daily
            "[\u00c9\u00d1\u0110L\u00c9\u0160\u0160\u00b7\u00b7\u00b7]",   // menu.endless
            "[L\u00c9\u011e\u00c1\u00c7\u00dd\u00b7\u00b7]",   // menu.legacy
            "[T\u00daT\u00d3R\u00cd\u00c1L\u00b7\u00b7\u00b7]",   // menu.tutorial
            "[\u00d1\u00d3 \u00c1\u0110\u0160\u00b7\u00b7]",   // menu.noAds
            "[F\u00cdR\u0160T T\u00cdM\u00c9?\u00b7\u00b7\u00b7\u00b7]",   // menu.offer.title
            "[L\u00e9\u00e1r\u00f1 th\u00e9 b\u00e1\u0161\u00ed\u00e7\u0161 \u00ed\u00f1 \u00e1 m\u00ed\u00f1\u00fat\u00e9.\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7]",   // menu.offer.line
            "[T\u00daT\u00d3R\u00cd\u00c1L\u00b7\u00b7\u00b7]",   // menu.offer.accept
            "[\u0160K\u00cdP\u00b7\u00b7]",   // menu.offer.skip
            "[\u0160\u00c9TT\u00cd\u00d1\u011e\u0160\u00b7\u00b7\u00b7]",   // settings.title
            "[PR\u00cdV\u00c1\u00c7\u00dd \u00d3PT\u00cd\u00d3\u00d1\u0160\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7]",   // settings.privacy
            "[L\u00c1\u00d1\u011e\u00da\u00c1\u011e\u00c9\u00b7\u00b7\u00b7]",   // settings.language
            "[\u00c9R\u00c1\u0160\u00c9\u0160 \u00c9V\u00c9R\u00dd L\u00c9V\u00c9L B\u00c9\u00c1T\u00c9\u00d1\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7]\n[\u00c1\u00d1\u0110 \u00c9V\u00c9R\u00dd \u0160\u00c7\u00d3R\u00c9. L\u00d3\u00c7K\u0160 \u00c1R\u00c9 K\u00c9PT.\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7]",   // settings.eraseCaption
            "[V\u00b7{0}   B\u00da\u00cdL\u0110 \u00b7\u00b7{1}]",   // settings.build
            "[\u00c9\u0110\u00cdT\u00d3R\u00b7\u00b7]",   // settings.buildEditor
            "[\u0160\u00d3\u00da\u00d1\u0110: \u00d3\u00d1\u00b7\u00b7\u00b7]",   // settings.soundOn
            "[\u0160\u00d3\u00da\u00d1\u0110: \u00d3FF\u00b7\u00b7\u00b7]",   // settings.soundOff
            "[R\u00c9\u0160\u00c9T PR\u00d3\u011eR\u00c9\u0160\u0160\u00b7\u00b7\u00b7\u00b7\u00b7]",   // settings.reset
            "[T\u00c1P \u00c1\u011e\u00c1\u00cd\u00d1 T\u00d3 \u00c9R\u00c1\u0160\u00c9\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7]",   // settings.resetArmed
            "[\u011eR\u00c9\u00c9\u00d1\u00b7\u00b7]",   // settings.skin.green
            "[BL\u00da\u00c9\u00b7\u00b7]",   // settings.skin.blue
            "[T\u00c1\u00d1\u00b7]",   // settings.skin.tan
            "[\u00c7L\u00c9\u00c1R\u00b7\u00b7]\n[\u00c1LL W\u00d3RL\u0110\u0160\u00b7\u00b7\u00b7\u00b7]",   // settings.skin.wantWorlds
            "[\u00c7L\u00c9\u00c1R\u00b7\u00b7]\n[\u00c1LL L\u00c9\u011e\u00c1\u00c7\u00dd\u00b7\u00b7\u00b7\u00b7]",   // settings.skin.wantLegacy
            "[H\u00d3W T\u00d3 PL\u00c1\u00dd\u00b7\u00b7\u00b7\u00b7]",   // rules.title
            "[\u00cd\u00f1f\u00e9\u00e7t \u00e9v\u00e9r\u00fd \u00e7\u00e9ll \u00f3\u00f1 th\u00e9 b\u00f3\u00e1r\u0111 t\u00f3 w\u00ed\u00f1.\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7]",   // rules.goal
            "[\u0110r\u00e1\u011f \u00e1 b\u00fa\u011f \u00f3\u00f1t\u00f3 \u00e1\u00f1\u00fd \u00e7\u00e9ll.\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7]",   // rules.intro
            "[\u00c1 r\u00e1\u00fd r\u00fa\u00f1\u0161 t\u00f3 th\u00e9 \u00e9\u0111\u011f\u00e9, \u00f3v\u00e9r \u011f\u00e1p\u0161.\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7]",   // rules.diagram
            "[W\u00ed\u00f1 \u00f3\u00f1 \u00e1 r\u00e9p\u00e9l \u00f3r tr\u00e1p \u00e1\u00f1\u0111 \u00edt \u0161t\u00edll \u00e7\u00f3\u00fa\u00f1t\u0161.\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7]",   // rules.note1
            "[H\u00edt \u00e1\u00f1 \u00e1v\u00f3\u00ed\u0111 \u00e7\u00e9ll \u00e1\u00f1\u0111 th\u00e9 \u0111r\u00f3p b\u00f3\u00fa\u00f1\u00e7\u00e9\u0161 b\u00e1\u00e7k.\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7]",   // rules.note2
            "[\u00cd\u00f1f\u00e9\u00e7t \u00edt.\u00b7\u00b7\u00b7]",   // rules.cell.infect
            "[\u011e\u00c1P\u00b7]",   // rules.cell.gap.name
            "[\u00d1\u00f3t \u00e1 \u00e7\u00e9ll: r\u00e1\u00fd\u0161 \u00e7r\u00f3\u0161\u0161 \u00edt.\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7]",   // rules.cell.gap.line
            "[W\u00c1LL\u00b7\u00b7]",   // rules.cell.wall.name
            "[Bl\u00f3\u00e7k\u0161 \u00e1 r\u00e1\u00fd.\u00b7\u00b7\u00b7\u00b7]",   // rules.cell.wall.line
            "[R\u00c9P\u00c9L\u00b7\u00b7]",   // rules.cell.repel.name
            "[\u00c7l\u00e9\u00e1r\u0161 b\u00e1\u00e7k wh\u00e9\u00f1 h\u00edt.\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7]",   // rules.cell.repel.line
            "[TR\u00c1P\u00b7\u00b7]",   // rules.cell.trap.name
            "[\u00c7l\u00e9\u00e1r\u0161 th\u00e9 b\u00f3\u00e1r\u0111 wh\u00e9\u00f1 h\u00edt.\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7]",   // rules.cell.trap.line
            "[R\u00c9L\u00c1\u00dd\u00b7\u00b7]",   // rules.cell.relay.name
            "[F\u00edr\u00e9\u0161 \u00edt\u0161 \u00f3w\u00f1 r\u00e1\u00fd\u0161 wh\u00e9\u00f1 h\u00edt.\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7]",   // rules.cell.relay.line
            "[\u00c1V\u00d3\u00cd\u0110\u00b7\u00b7]",   // rules.cell.avoid.name
            "[R\u00e1\u00fd\u0161 m\u00fa\u0161t \u00f1\u00f3t t\u00f3\u00fa\u00e7h \u00edt.\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7]",   // rules.cell.avoid.line
            "[R\u00e1\u00fd\u0161 r\u00fa\u00f1 t\u00f3 th\u00e9 \u00e9\u0111\u011f\u00e9.\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7]",   // rules.spread.cardinal
            "[\u00d3r \u00e7\u00f3r\u00f1\u00e9r t\u00f3 \u00e7\u00f3r\u00f1\u00e9r.\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7]",   // rules.spread.diagonal
            "[\u00c1 bl\u00f3t t\u00e1k\u00e9\u0161 th\u00e9 \u00e9\u00ed\u011fht \u00e1r\u00f3\u00fa\u00f1\u0111 \u00edt.\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7]",   // rules.spread.area
            "[L\u00c9\u011e\u00c1\u00c7\u00dd\u00b7\u00b7]",   // legacy.title
            "[FR\u00c9\u00c9 PL\u00c1\u00dd\u00b7\u00b7\u00b7]",   // freeplay.title
            "[B\u00c9\u011e\u00cd\u00d1\u00d1\u00c9R\u00b7\u00b7\u00b7]",   // freeplay.difficulty.beginner
            "[\u00c9\u00c1\u0160\u00dd\u00b7\u00b7]",   // freeplay.difficulty.easy
            "[M\u00c9\u0110\u00cd\u00daM\u00b7\u00b7]",   // freeplay.difficulty.medium
            "[H\u00c1R\u0110\u00b7\u00b7]",   // freeplay.difficulty.hard
            "[\u00c7H\u00c1LL\u00c9\u00d1\u011e\u00cd\u00d1\u011e\u00b7\u00b7\u00b7\u00b7]",   // freeplay.difficulty.challenging
            "[W\u00d3RL\u0110\u0160\u00b7\u00b7]",   // worlds.title
            "[{0}  {1}]",   // worlds.row
            "[{0}/{1}]",   // worlds.progress
            "[\u0110\u00c1\u00cdL\u00dd\u00b7\u00b7]",   // daily.title
            "[T\u00d3\u0110\u00c1\u00dd\u00b7\u00b7]",   // daily.today
            "[P\u00c1\u0160T\u00b7\u00b7]",   // daily.past
            "[\u0160TR\u00c9\u00c1K \u00b7\u00b7{0:00}]",   // daily.streak
            "[{0} {1:00}/{2:00}]",   // daily.monthCount
            "[{0} {1:00} {2}]",   // daily.dateLine
            "[B\u00da\u011e\u0160 \u00b7\u00b7{0}]",   // daily.bugs
            "[\u00c7\u00c9LL\u0160 \u00b7\u00b7{0}]",   // daily.cells
            "[\u00c7\u00d3MPL\u00c9T\u00c9\u00b7\u00b7\u00b7]",   // daily.complete
            "[\u011e\u00c9\u00d1\u00c9R\u00c1T\u00cd\u00d1\u011e\u00b7\u00b7\u00b7\u00b7]",   // daily.generating
            "[\u00da\u00d1PL\u00c1\u00dd\u00c9\u0110\u00b7\u00b7\u00b7]",   // daily.unplayed
            "[PL\u00c1\u00dd \u00c1\u011e\u00c1\u00cd\u00d1\u00b7\u00b7\u00b7\u00b7]",   // daily.playAgain
            "[B\u00c9\u011e\u00cd\u00d1\u00b7\u00b7]",   // daily.begin
            "[\u00c9\u00d1\u0110L\u00c9\u0160\u0160\u00b7\u00b7\u00b7]",   // endless.title
            "[B\u00c9\u0160T \u00b7\u00b7{0}]",   // endless.best
            "[R\u00c9\u0160\u00c9T\u00b7\u00b7]",   // board.reset
            "[L\u00c9\u011e\u00c1\u00c7\u00dd\u00b7\u00b7]",   // board.legacy
            "[\u0110\u00c1\u00cdL\u00dd\u00b7\u00b7]",   // board.daily
            "[\u00c9\u00d1\u0110L\u00c9\u0160\u0160  \u00b7\u00b7\u00b7{0}]",   // board.endless
            "[L\u00c9V\u00c9L \u00b7\u00b7{0}]",   // board.level
            "[T\u00daT\u00d3R\u00cd\u00c1L \u00b7\u00b7\u00b7{0}/{1}]",   // board.tutorialTitle
            "[B\u00c9\u011e\u00cd\u00d1\u00b7\u00b7]",   // board.begin
            "[H\u00cd\u00d1T\u00b7\u00b7]",   // board.hint
            "[+1 \u0160\u00d3LV\u00c9\u00b7\u00b7]",   // board.plusSolve
            "[\u0160\u00d3LV\u00c9 \u00b7\u00b7{0:00}]",   // board.solve
            "[\u00c7\u00d3MPL\u00c9T\u00c9\u00b7\u00b7\u00b7]",   // board.complete
            "[\u00c7\u00d3MPL\u00c9T\u00c9\u00b7\u00b7\u00b7]\n[\u0160tr\u00e9\u00e1k \u0161t\u00e1rt\u00e9\u0111\u00b7\u00b7\u00b7\u00b7\u00b7]",   // board.completeStreakStarted
            "[\u00c7\u00d3MPL\u00c9T\u00c9\u00b7\u00b7\u00b7]\n[{0} \u0111\u00e1\u00fd\u0161 \u00ed\u00f1 \u00e1 r\u00f3w\u00b7\u00b7\u00b7\u00b7]",   // board.completeStreakDays
            "[T\u00daT\u00d3R\u00cd\u00c1L \u00c7\u00d3MPL\u00c9T\u00c9\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7]",   // board.tutorialComplete
            "[M\u00c9\u00d1\u00da\u00b7\u00b7]",   // board.popup.menu
            "[R\u00c9PL\u00c1\u00dd\u00b7\u00b7]",   // board.popup.replay
            "[\u00d1\u00c9XT\u00b7\u00b7]",   // board.popup.next
            "[PL\u00c1\u00dd\u00b7\u00b7]",   // board.popup.play
            "[\u00c7\u00c1L\u00c9\u00d1\u0110\u00c1R\u00b7\u00b7\u00b7]",   // board.popup.calendar
            "[\u0160\u00d3LV\u00c9\u0110 \u00b7\u00b7{0}]",   // board.hud.solved
            "[\u0160TR\u00c9\u00c1K \u00b7\u00b7{0}]",   // board.hud.streak
            "[B\u00c9\u0160T \u00b7\u00b7{0}]",   // board.hud.best
            "[{0}/5]",   // board.hud.runCount
            "[T\u00cd\u00c9R \u00b7\u00b7{0}]",   // tier.name
            "[T\u00b7{0}]",   // tier.short
            "[{0}-{1}]",   // tier.band
            "[L\u00d3\u00c1\u0110\u00cd\u00d1\u011e\u00b7\u00b7\u00b7]",   // loading.caption
            "[L\u00c1\u00d1\u011e\u00da\u00c1\u011e\u00c9\u00b7\u00b7\u00b7]",   // language.title
            "[\u00c1\u00daT\u00d3\u00b7\u00b7]",   // language.auto
            "[M\u00d3\u00d1\u00b7]",   // cal.day.1
            "[T\u00da\u00c9\u00b7]",   // cal.day.2
            "[W\u00c9\u0110\u00b7]",   // cal.day.3
            "[TH\u00da\u00b7]",   // cal.day.4
            "[FR\u00cd\u00b7]",   // cal.day.5
            "[\u0160\u00c1T\u00b7]",   // cal.day.6
            "[\u0160\u00da\u00d1\u00b7]",   // cal.day.7
            "[J\u00c1\u00d1\u00da\u00c1R\u00dd\u00b7\u00b7\u00b7]",   // cal.month.1
            "[F\u00c9BR\u00da\u00c1R\u00dd\u00b7\u00b7\u00b7]",   // cal.month.2
            "[M\u00c1R\u00c7H\u00b7\u00b7]",   // cal.month.3
            "[\u00c1PR\u00cdL\u00b7\u00b7]",   // cal.month.4
            "[M\u00c1\u00dd\u00b7]",   // cal.month.5
            "[J\u00da\u00d1\u00c9\u00b7\u00b7]",   // cal.month.6
            "[J\u00daL\u00dd\u00b7\u00b7]",   // cal.month.7
            "[\u00c1\u00da\u011e\u00da\u0160T\u00b7\u00b7]",   // cal.month.8
            "[\u0160\u00c9PT\u00c9MB\u00c9R\u00b7\u00b7\u00b7\u00b7]",   // cal.month.9
            "[\u00d3\u00c7T\u00d3B\u00c9R\u00b7\u00b7\u00b7]",   // cal.month.10
            "[\u00d1\u00d3V\u00c9MB\u00c9R\u00b7\u00b7\u00b7]",   // cal.month.11
            "[\u0110\u00c9\u00c7\u00c9MB\u00c9R\u00b7\u00b7\u00b7]",   // cal.month.12
            "[J\u00c1\u00d1\u00b7]",   // cal.month.1.short
            "[F\u00c9B\u00b7]",   // cal.month.2.short
            "[M\u00c1R\u00b7]",   // cal.month.3.short
            "[\u00c1PR\u00b7]",   // cal.month.4.short
            "[M\u00c1\u00dd\u00b7]",   // cal.month.5.short
            "[J\u00da\u00d1\u00b7]",   // cal.month.6.short
            "[J\u00daL\u00b7]",   // cal.month.7.short
            "[\u00c1\u00da\u011e\u00b7]",   // cal.month.8.short
            "[\u0160\u00c9P\u00b7]",   // cal.month.9.short
            "[\u00d3\u00c7T\u00b7]",   // cal.month.10.short
            "[\u00d1\u00d3V\u00b7]",   // cal.month.11.short
            "[\u0110\u00c9\u00c7\u00b7]",   // cal.month.12.short
            "[\u0110r\u00e1\u011f th\u00e9 b\u00fa\u011f \u00f3\u00f1t\u00f3 th\u00e9 m\u00e1rk\u00e9\u0111 \u00e7\u00e9ll.\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7]",   // tut.1.line
            "[R\u00e1\u00fd\u0161 \u00e7r\u00f3\u0161\u0161 \u011f\u00e1p\u0161.\u00b7\u00b7\u00b7\u00b7\u00b7]",   // tut.2.line
            "[Tw\u00f3 b\u00fa\u011f\u0161. T\u00e1p \u00e1 pl\u00e1\u00e7\u00e9\u0111 b\u00fa\u011f t\u00f3 p\u00ed\u00e7k \u00edt \u00fap.\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7]",   // tut.3.line
            "[\u00c1 w\u00e1ll \u0161t\u00f3p\u0161 \u00e1 r\u00e1\u00fd.\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7]",   // tut.4.line
            "[B\u00fa\u011f\u0161 \u00e7\u00e1\u00f1 \u00e1l\u0161\u00f3 b\u00e9 \u0111\u00ed\u00e1\u011f\u00f3\u00f1\u00e1l.\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7]",   // tut.5.line
            "[\u00c1 bl\u00f3t t\u00e1k\u00e9\u0161 th\u00e9 \u00e9\u00ed\u011fht \u00e7\u00e9ll\u0161 \u00e1r\u00f3\u00fa\u00f1\u0111 \u00edt.\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7]",   // tut.6.line
            "[\u00c1 r\u00e1\u00fd m\u00e1\u00fd \u00f1\u00e9v\u00e9r t\u00f3\u00fa\u00e7h \u00e1\u00f1 \u00e1v\u00f3\u00ed\u0111 \u00e7\u00e9ll.\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7]",   // tut.7.line
            "[\u00c1 r\u00e9p\u00e9l \u00e7l\u00e9\u00e1r\u0161 th\u00e9 r\u00e1\u00fd th\u00e1t h\u00edt \u00edt.\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7]",   // tut.8.line
            "[\u00c1 tr\u00e1p r\u00e9\u0161\u00e9t\u0161 th\u00e9 wh\u00f3l\u00e9 b\u00f3\u00e1r\u0111.\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7]",   // tut.9.line
            "[\u00c1 r\u00e9l\u00e1\u00fd f\u00edr\u00e9\u0161 \u00edt\u0161 \u00f3w\u00f1 r\u00e1\u00fd\u0161 wh\u00e9\u00f1 l\u00edt.\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7]",   // tut.10.line
            "[F\u00cdR\u0160T \u0160T\u00c9P\u0160\u00b7\u00b7\u00b7\u00b7]",   // world.w01.name
            "[TW\u00d3 L\u00cd\u00d1\u00c9\u0160\u00b7\u00b7\u00b7]",   // world.w02.name
            "[\u00c7\u00d3R\u00d1\u00c9R\u0160\u00b7\u00b7\u00b7]",   // world.w03.name
            "[\u00c7R\u00d3\u0160\u0160\u00cd\u00d1\u011e\u0160\u00b7\u00b7\u00b7\u00b7]",   // world.w04.name
            "[K\u00c9\u00c9P \u00c7L\u00c9\u00c1\u00d1\u00b7\u00b7\u00b7\u00b7]",   // world.w05.name
            "[\u00c7\u00d3\u00da\u00d1T\u00cd\u00d1\u011e\u00b7\u00b7\u00b7]",   // world.w06.name
            "[\u00c7\u00d3RR\u00cd\u0110\u00d3R\u0160\u00b7\u00b7\u00b7\u00b7]",   // world.w07.name
            "[BL\u00d3T\u0160\u00b7\u00b7]",   // world.w08.name
            "[L\u00d3\u00d1\u011e R\u00c9\u00c1\u00c7H\u00b7\u00b7\u00b7\u00b7]",   // world.w09.name
            "[F\u00d3\u00daR \u00c1RM\u0160\u00b7\u00b7\u00b7]",   // world.w10.name
            "[\u0110\u00cd\u00c1\u011e\u00d3\u00d1\u00c1L\u0160\u00b7\u00b7\u00b7\u00b7]",   // world.w11.name
            "[T\u00cd\u011eHT\u00b7\u00b7]",   // world.w12.name
            "[R\u00c9L\u00c1\u00dd\u0160\u00b7\u00b7]",   // world.w14.name
            "[\u00c7R\u00d3\u0160\u0160T\u00c1LK\u00b7\u00b7\u00b7\u00b7]",   // world.w15.name
            "[\u0160\u00daPP\u00d3\u0160\u00c9\u00b7\u00b7\u00b7]",   // world.w16.name
            "[M\u00c1\u0160T\u00c9R\u00dd\u00b7\u00b7\u00b7]",   // world.w17.name
        };

        // qps-plocm
        static readonly string[] QpsPlocm =
        {
            "UNEM",   // nav.menu
            "SDLROW",   // nav.worlds
            "SGNITTES",   // nav.settings
            "{0}/{1}",   // common.page
            "SDLROW",   // menu.worlds
            "YLIAD",   // menu.daily
            "SSELDNE",   // menu.endless
            "YCAGEL",   // menu.legacy
            "LAIROTUT",   // menu.tutorial
            "SDA ON",   // menu.noAds
            "?EMIT TSRIF",   // menu.offer.title
            ".etunim a ni scisab eht nraeL",   // menu.offer.line
            "LAIROTUT",   // menu.offer.accept
            "PIKS",   // menu.offer.skip
            "SGNITTES",   // settings.title
            "SNOITPO YCAVIRP",   // settings.privacy
            "EGAUGNAL",   // settings.language
            "NETAEB LEVEL YREVE SESARE\n.TPEK ERA SKCOL .EROCS YREVE DNA",   // settings.eraseCaption
            "V{0} DLIUB   {1}",   // settings.build
            "ROTIDE",   // settings.buildEditor
            "NO :DNUOS",   // settings.soundOn
            "FFO :DNUOS",   // settings.soundOff
            "SSERGORP TESER",   // settings.reset
            "ESARE OT NIAGA PAT",   // settings.resetArmed
            "NEERG",   // settings.skin.green
            "EULB",   // settings.skin.blue
            "NAT",   // settings.skin.tan
            "RAELC\nSDLROW LLA",   // settings.skin.wantWorlds
            "RAELC\nYCAGEL LLA",   // settings.skin.wantLegacy
            "YALP OT WOH",   // rules.title
            ".niw ot draob eht no llec yreve tcefnI",   // rules.goal
            ".llec yna otno gub a garD",   // rules.intro
            ".spag revo ,egde eht ot snur yar A",   // rules.diagram
            ".stnuoc llits ti dna part ro leper a no niW",   // rules.note1
            ".kcab secnuob pord eht dna llec diova na tiH",   // rules.note2
            ".ti tcefnI",   // rules.cell.infect
            "PAG",   // rules.cell.gap.name
            ".ti ssorc syar :llec a toN",   // rules.cell.gap.line
            "LLAW",   // rules.cell.wall.name
            ".yar a skcolB",   // rules.cell.wall.line
            "LEPER",   // rules.cell.repel.name
            ".tih nehw kcab sraelC",   // rules.cell.repel.line
            "PART",   // rules.cell.trap.name
            ".tih nehw draob eht sraelC",   // rules.cell.trap.line
            "YALER",   // rules.cell.relay.name
            ".tih nehw syar nwo sti seriF",   // rules.cell.relay.line
            "DIOVA",   // rules.cell.avoid.name
            ".ti hcuot ton tsum syaR",   // rules.cell.avoid.line
            ".egde eht ot nur syaR",   // rules.spread.cardinal
            ".renroc ot renroc rO",   // rules.spread.diagonal
            ".ti dnuora thgie eht sekat tolb A",   // rules.spread.area
            "YCAGEL",   // legacy.title
            "YALP EERF",   // freeplay.title
            "RENNIGEB",   // freeplay.difficulty.beginner
            "YSAE",   // freeplay.difficulty.easy
            "MUIDEM",   // freeplay.difficulty.medium
            "DRAH",   // freeplay.difficulty.hard
            "GNIGNELLAHC",   // freeplay.difficulty.challenging
            "SDLROW",   // worlds.title
            "{0}  {1}",   // worlds.row
            "{0}/{1}",   // worlds.progress
            "YLIAD",   // daily.title
            "YADOT",   // daily.today
            "TSAP",   // daily.past
            " KAERTS{0:00}",   // daily.streak
            "{0} {1:00}/{2:00}",   // daily.monthCount
            "{0} {1:00} {2}",   // daily.dateLine
            " SGUB{0}",   // daily.bugs
            " SLLEC{0}",   // daily.cells
            "ETELPMOC",   // daily.complete
            "GNITARENEG",   // daily.generating
            "DEYALPNU",   // daily.unplayed
            "NIAGA YALP",   // daily.playAgain
            "NIGEB",   // daily.begin
            "SSELDNE",   // endless.title
            " TSEB{0}",   // endless.best
            "TESER",   // board.reset
            "YCAGEL",   // board.legacy
            "YLIAD",   // board.daily
            "  SSELDNE{0}",   // board.endless
            " LEVEL{0}",   // board.level
            " LAIROTUT{0}/{1}",   // board.tutorialTitle
            "NIGEB",   // board.begin
            "TNIH",   // board.hint
            "EVLOS 1+",   // board.plusSolve
            " EVLOS{0:00}",   // board.solve
            "ETELPMOC",   // board.complete
            "ETELPMOC\ndetrats kaertS",   // board.completeStreakStarted
            "ETELPMOC\n{0}wor a ni syad ",   // board.completeStreakDays
            "ETELPMOC LAIROTUT",   // board.tutorialComplete
            "UNEM",   // board.popup.menu
            "YALPER",   // board.popup.replay
            "TXEN",   // board.popup.next
            "YALP",   // board.popup.play
            "RADNELAC",   // board.popup.calendar
            " DEVLOS{0}",   // board.hud.solved
            " KAERTS{0}",   // board.hud.streak
            " TSEB{0}",   // board.hud.best
            "{0}5/",   // board.hud.runCount
            " REIT{0}",   // tier.name
            "T{0}",   // tier.short
            "{0}-{1}",   // tier.band
            "GNIDAOL",   // loading.caption
            "EGAUGNAL",   // language.title
            "OTUA",   // language.auto
            "NOM",   // cal.day.1
            "EUT",   // cal.day.2
            "DEW",   // cal.day.3
            "UHT",   // cal.day.4
            "IRF",   // cal.day.5
            "TAS",   // cal.day.6
            "NUS",   // cal.day.7
            "YRAUNAJ",   // cal.month.1
            "YRAURBEF",   // cal.month.2
            "HCRAM",   // cal.month.3
            "LIRPA",   // cal.month.4
            "YAM",   // cal.month.5
            "ENUJ",   // cal.month.6
            "YLUJ",   // cal.month.7
            "TSUGUA",   // cal.month.8
            "REBMETPES",   // cal.month.9
            "REBOTCO",   // cal.month.10
            "REBMEVON",   // cal.month.11
            "REBMECED",   // cal.month.12
            "NAJ",   // cal.month.1.short
            "BEF",   // cal.month.2.short
            "RAM",   // cal.month.3.short
            "RPA",   // cal.month.4.short
            "YAM",   // cal.month.5.short
            "NUJ",   // cal.month.6.short
            "LUJ",   // cal.month.7.short
            "GUA",   // cal.month.8.short
            "PES",   // cal.month.9.short
            "TCO",   // cal.month.10.short
            "VON",   // cal.month.11.short
            "CED",   // cal.month.12.short
            ".llec dekram eht otno gub eht garD",   // tut.1.line
            ".spag ssorc syaR",   // tut.2.line
            ".pu ti kcip ot gub decalp a paT .sgub owT",   // tut.3.line
            ".yar a spots llaw A",   // tut.4.line
            ".lanogaid eb osla nac sguB",   // tut.5.line
            ".ti dnuora sllec thgie eht sekat tolb A",   // tut.6.line
            ".llec diova na hcuot reven yam yar A",   // tut.7.line
            ".ti tih taht yar eht sraelc leper A",   // tut.8.line
            ".draob elohw eht steser part A",   // tut.9.line
            ".til nehw syar nwo sti serif yaler A",   // tut.10.line
            "SPETS TSRIF",   // world.w01.name
            "SENIL OWT",   // world.w02.name
            "SRENROC",   // world.w03.name
            "SGNISSORC",   // world.w04.name
            "NAELC PEEK",   // world.w05.name
            "GNITNUOC",   // world.w06.name
            "SRODIRROC",   // world.w07.name
            "STOLB",   // world.w08.name
            "HCAER GNOL",   // world.w09.name
            "SMRA RUOF",   // world.w10.name
            "SLANOGAID",   // world.w11.name
            "THGIT",   // world.w12.name
            "SYALER",   // world.w14.name
            "KLATSSORC",   // world.w15.name
            "ESOPPUS",   // world.w16.name
            "YRETSAM",   // world.w17.name
        };

        static readonly string[][] Tables =
        {
            En,
            QpsPloc,
            QpsPlocm,
        };

        static string[] _v = Tables[0];
        static int _tag;

        // The tag in force. Set through Str.Use (Strings.cs).
        public static string CurrentTag => Tags[_tag];

        static void Bind(int tag)
        {
            _tag = tag;
            _v = Tables[tag];
        }

        // ---- families ----

        static readonly int[] MonthIdx = { 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123 };
        static readonly int[] MonthShortIdx = { 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135 };
        static readonly int[] DayIdx = { 105, 106, 107, 108, 109, 110, 111 };
        static readonly int[] TutIdx = { 136, 137, 138, 139, 140, 141, 142, 143, 144, 145 };
        static readonly int[] DifficultyIdx = { 53, 54, 55, 56, 57 };

        // Month 1-12, weekday 1-7 Monday first, tutorial step 1-based,
        // difficulty by its enum ordinal. Out of range is a bug, not a
        // missing translation, so these throw rather than blank.
        public static string Month(int month) => _v[MonthIdx[month - 1]];
        public static string MonthShort(int month) => _v[MonthShortIdx[month - 1]];
        public static string Day(int isoWeekday) => _v[DayIdx[isoWeekday - 1]];
        public static string TutorialLine(int step) => _v[TutIdx[step - 1]];
        public static string DifficultyName(int ordinal) => _v[DifficultyIdx[ordinal]];

        public static string WorldName(string worldId)
        {
            switch (worldId)
            {
                case "w01": return _v[146];
                case "w02": return _v[147];
                case "w03": return _v[148];
                case "w04": return _v[149];
                case "w05": return _v[150];
                case "w06": return _v[151];
                case "w07": return _v[152];
                case "w08": return _v[153];
                case "w09": return _v[154];
                case "w10": return _v[155];
                case "w11": return _v[156];
                case "w12": return _v[157];
                case "w14": return _v[158];
                case "w15": return _v[159];
                case "w16": return _v[160];
                case "w17": return _v[161];
            }
            return worldId;
        }

        // ---- keys ----

        public static string NavMenu => _v[0];
        public static string NavWorlds => _v[1];
        public static string NavSettings => _v[2];
        public static string CommonPage => _v[3];
        public static string MenuWorlds => _v[4];
        public static string MenuDaily => _v[5];
        public static string MenuEndless => _v[6];
        public static string MenuLegacy => _v[7];
        public static string MenuTutorial => _v[8];
        public static string MenuNoAds => _v[9];
        public static string MenuOfferTitle => _v[10];
        public static string MenuOfferLine => _v[11];
        public static string MenuOfferAccept => _v[12];
        public static string MenuOfferSkip => _v[13];
        public static string SettingsTitle => _v[14];
        public static string SettingsPrivacy => _v[15];
        public static string SettingsLanguage => _v[16];
        public static string SettingsEraseCaption => _v[17];
        public static string SettingsBuild => _v[18];
        public static string SettingsBuildEditor => _v[19];
        public static string SettingsSoundOn => _v[20];
        public static string SettingsSoundOff => _v[21];
        public static string SettingsReset => _v[22];
        public static string SettingsResetArmed => _v[23];
        public static string SettingsSkinGreen => _v[24];
        public static string SettingsSkinBlue => _v[25];
        public static string SettingsSkinTan => _v[26];
        public static string SettingsSkinWantWorlds => _v[27];
        public static string SettingsSkinWantLegacy => _v[28];
        public static string RulesTitle => _v[29];
        public static string RulesGoal => _v[30];
        public static string RulesIntro => _v[31];
        public static string RulesDiagram => _v[32];
        public static string RulesNote1 => _v[33];
        public static string RulesNote2 => _v[34];
        public static string RulesCellInfect => _v[35];
        public static string RulesCellGapName => _v[36];
        public static string RulesCellGapLine => _v[37];
        public static string RulesCellWallName => _v[38];
        public static string RulesCellWallLine => _v[39];
        public static string RulesCellRepelName => _v[40];
        public static string RulesCellRepelLine => _v[41];
        public static string RulesCellTrapName => _v[42];
        public static string RulesCellTrapLine => _v[43];
        public static string RulesCellRelayName => _v[44];
        public static string RulesCellRelayLine => _v[45];
        public static string RulesCellAvoidName => _v[46];
        public static string RulesCellAvoidLine => _v[47];
        public static string RulesSpreadCardinal => _v[48];
        public static string RulesSpreadDiagonal => _v[49];
        public static string RulesSpreadArea => _v[50];
        public static string LegacyTitle => _v[51];
        public static string FreeplayTitle => _v[52];
        public static string FreeplayDifficultyBeginner => _v[53];
        public static string FreeplayDifficultyEasy => _v[54];
        public static string FreeplayDifficultyMedium => _v[55];
        public static string FreeplayDifficultyHard => _v[56];
        public static string FreeplayDifficultyChallenging => _v[57];
        public static string WorldsTitle => _v[58];
        public static string WorldsRow => _v[59];
        public static string WorldsProgress => _v[60];
        public static string DailyTitle => _v[61];
        public static string DailyToday => _v[62];
        public static string DailyPast => _v[63];
        public static string DailyStreak => _v[64];
        public static string DailyMonthCount => _v[65];
        public static string DailyDateLine => _v[66];
        public static string DailyBugs => _v[67];
        public static string DailyCells => _v[68];
        public static string DailyComplete => _v[69];
        public static string DailyGenerating => _v[70];
        public static string DailyUnplayed => _v[71];
        public static string DailyPlayAgain => _v[72];
        public static string DailyBegin => _v[73];
        public static string EndlessTitle => _v[74];
        public static string EndlessBest => _v[75];
        public static string BoardReset => _v[76];
        public static string BoardLegacy => _v[77];
        public static string BoardDaily => _v[78];
        public static string BoardEndless => _v[79];
        public static string BoardLevel => _v[80];
        public static string BoardTutorialTitle => _v[81];
        public static string BoardBegin => _v[82];
        public static string BoardHint => _v[83];
        public static string BoardPlusSolve => _v[84];
        public static string BoardSolve => _v[85];
        public static string BoardComplete => _v[86];
        public static string BoardCompleteStreakStarted => _v[87];
        public static string BoardCompleteStreakDays => _v[88];
        public static string BoardTutorialComplete => _v[89];
        public static string BoardPopupMenu => _v[90];
        public static string BoardPopupReplay => _v[91];
        public static string BoardPopupNext => _v[92];
        public static string BoardPopupPlay => _v[93];
        public static string BoardPopupCalendar => _v[94];
        public static string BoardHudSolved => _v[95];
        public static string BoardHudStreak => _v[96];
        public static string BoardHudBest => _v[97];
        public static string BoardHudRunCount => _v[98];
        public static string TierName => _v[99];
        public static string TierShort => _v[100];
        public static string TierBand => _v[101];
        public static string LoadingCaption => _v[102];
        public static string LanguageTitle => _v[103];
        public static string LanguageAuto => _v[104];
        public static string CalDay1 => _v[105];
        public static string CalDay2 => _v[106];
        public static string CalDay3 => _v[107];
        public static string CalDay4 => _v[108];
        public static string CalDay5 => _v[109];
        public static string CalDay6 => _v[110];
        public static string CalDay7 => _v[111];
        public static string CalMonth1 => _v[112];
        public static string CalMonth2 => _v[113];
        public static string CalMonth3 => _v[114];
        public static string CalMonth4 => _v[115];
        public static string CalMonth5 => _v[116];
        public static string CalMonth6 => _v[117];
        public static string CalMonth7 => _v[118];
        public static string CalMonth8 => _v[119];
        public static string CalMonth9 => _v[120];
        public static string CalMonth10 => _v[121];
        public static string CalMonth11 => _v[122];
        public static string CalMonth12 => _v[123];
        public static string CalMonth1Short => _v[124];
        public static string CalMonth2Short => _v[125];
        public static string CalMonth3Short => _v[126];
        public static string CalMonth4Short => _v[127];
        public static string CalMonth5Short => _v[128];
        public static string CalMonth6Short => _v[129];
        public static string CalMonth7Short => _v[130];
        public static string CalMonth8Short => _v[131];
        public static string CalMonth9Short => _v[132];
        public static string CalMonth10Short => _v[133];
        public static string CalMonth11Short => _v[134];
        public static string CalMonth12Short => _v[135];
        public static string Tut1Line => _v[136];
        public static string Tut2Line => _v[137];
        public static string Tut3Line => _v[138];
        public static string Tut4Line => _v[139];
        public static string Tut5Line => _v[140];
        public static string Tut6Line => _v[141];
        public static string Tut7Line => _v[142];
        public static string Tut8Line => _v[143];
        public static string Tut9Line => _v[144];
        public static string Tut10Line => _v[145];
        public static string WorldW01Name => _v[146];
        public static string WorldW02Name => _v[147];
        public static string WorldW03Name => _v[148];
        public static string WorldW04Name => _v[149];
        public static string WorldW05Name => _v[150];
        public static string WorldW06Name => _v[151];
        public static string WorldW07Name => _v[152];
        public static string WorldW08Name => _v[153];
        public static string WorldW09Name => _v[154];
        public static string WorldW10Name => _v[155];
        public static string WorldW11Name => _v[156];
        public static string WorldW12Name => _v[157];
        public static string WorldW14Name => _v[158];
        public static string WorldW15Name => _v[159];
        public static string WorldW16Name => _v[160];
        public static string WorldW17Name => _v[161];
    }
}
