// <auto-generated> grid-infect-style/gen-logo.mjs --cs. Do not edit; regenerate.
// The wordmark's letters (Chakra Petch Bold, OFL, grid-infect-style/fonts)
// as flattened outlines in 1/1000 em, y down, baseline 0, and the two words'
// pen positions at the lock's 92 px / 2 px letter-spacing (STYLE-GUIDE §12).
namespace GridInfect.Game
{
    public static class LogoGlyphs
    {
        public const float Em = 1000f;                 // outline units per em
        public const float FontPx = 92f;                // the lock's type size
        public const float GapPx = 96f;                 // GRID | gap | INFECT
        public const float BugPx = 56f;                 // bug_E in the gap
        public const float BaselineBelowMid = 0.36f;   // baseline = mid + FontPx * this

        public static readonly string Grid = "GRID";
        public static readonly float[] GridPen = { 0f, 697.7f, 1394.5f, 1692.2f };
        public const float GridWidth = 2402.0f;
        public static readonly string Infect = "INFECT";
        public static readonly float[] InfectPen = { 0f, 297.7f, 1016.5f, 1614.2f, 2242f, 2913.7f };
        public const float InfectWidth = 3519.4f;

        public static float[][] Contours(char c)
        {
            switch (c)
            {
                case 'G': return G;
                case 'R': return R;
                case 'I': return I;
                case 'D': return D;
                case 'N': return N;
                case 'F': return F;
                case 'E': return E;
                case 'C': return C;
                case 'T': return T;
                default: return null;
            }
        }

        static readonly float[][] G =
        {
            new float[] { 170f, 0f, 55f, -115f, 55f, -585f, 170f, -700f, 518f, -700f, 631f, -587f, 631f, -480f, 495f, -480f, 495f, -537f, 448f, -584f, 242f, -584f, 191f, -533f, 191f, -167f, 242f, -116f, 450f, -116f, 499f, -165f, 499f, -274f, 349f, -274f, 349f, -390f, 631f, -390f, 631f, -115f, 516f, 0f, 170f, 0f },
        };

        static readonly float[][] R =
        {
            new float[] { 543f, -311f, 615f, -232f, 615f, 0f, 479f, 0f, 479f, -201f, 419f, -268f, 201f, -268f, 201f, 0f, 65f, 0f, 65f, -700f, 504f, -700f, 611f, -592f, 611f, -380f, 543f, -311f },
            new float[] { 201f, -586f, 201f, -380f, 442f, -380f, 477f, -415f, 477f, -551f, 442f, -586f, 201f, -586f },
        };

        static readonly float[][] I =
        {
            new float[] { 70f, 0f, 70f, -700f, 206f, -700f, 206f, 0f, 70f, 0f },
        };

        static readonly float[][] D =
        {
            new float[] { 65f, 0f, 65f, -700f, 513f, -700f, 633f, -580f, 633f, -120f, 513f, 0f, 65f, 0f },
            new float[] { 201f, -116f, 446f, -116f, 497f, -167f, 497f, -533f, 446f, -584f, 201f, -584f, 201f, -116f },
        };

        static readonly float[][] N =
        {
            new float[] { 65f, 0f, 65f, -700f, 187f, -700f, 499f, -225f, 501f, -225f, 501f, -700f, 632f, -700f, 632f, 0f, 510f, 0f, 198f, -474f, 196f, -474f, 196f, 0f, 65f, 0f },
        };

        static readonly float[][] F =
        {
            new float[] { 65f, 0f, 65f, -700f, 561f, -700f, 561f, -585f, 201f, -585f, 201f, -391f, 513f, -391f, 513f, -276f, 201f, -276f, 201f, 0f, 65f, 0f },
        };

        static readonly float[][] E =
        {
            new float[] { 65f, 0f, 65f, -700f, 571f, -700f, 571f, -585f, 201f, -585f, 201f, -408f, 542f, -408f, 542f, -295f, 201f, -295f, 201f, -115f, 571f, -115f, 571f, 0f, 65f, 0f },
        };

        static readonly float[][] C =
        {
            new float[] { 170f, 0f, 55f, -115f, 55f, -585f, 170f, -700f, 512f, -700f, 625f, -587f, 625f, -480f, 489f, -480f, 489f, -537f, 442f, -584f, 242f, -584f, 191f, -533f, 191f, -167f, 242f, -116f, 442f, -116f, 489f, -163f, 489f, -220f, 625f, -220f, 625f, -113f, 512f, 0f, 170f, 0f },
        };

        static readonly float[][] T =
        {
            new float[] { 224f, 0f, 224f, -585f, 15f, -585f, 15f, -700f, 569f, -700f, 569f, -585f, 360f, -585f, 360f, 0f, 224f, 0f },
        };
    }
}
