#Contains API Secret used to validate your application. Commit to internal source control; avoid making secret public.
#Tue Jun 10 13:12:31 EDT 2014
apiSecret=0925af1353c19ef3d09ed22c3226a53efb7933af64aeeea81b623e1e04585ab8
