#!/usr/bin/env python3
"""Bake the 128 classic levels from docs/test_vectors.json into
unity/Assets/_Project/Core/Levels/ClassicLevelData.g.cs.

The vectors are the single source of truth for level data (REQUIREMENTS
R-102); this script is the mechanical derivation. Re-run after any change to
the vectors:

    python3 tools/bake_levels.py

Output is deterministic: same input, same bytes.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VECTORS = os.path.join(ROOT, "docs", "test_vectors.json")
OUTPUT = os.path.join(
    ROOT, "unity", "Assets", "_Project", "Core", "Levels", "ClassicLevelData.g.cs")

HEADER = """\
// <auto-generated>
// Generated by tools/bake_levels.py from docs/test_vectors.json.
// Do not edit; re-run the script instead.
// Boards: 66 chars, row-major, digits = cell values (RULES.md §1.1).
// Pieces: ordered tile names, comma-joined.
// Solutions: the recorded solution as "piece@cell" pairs in vector order
// (stage 5: the Lock tool's fallback source in Legacy mode).
// </auto-generated>

namespace GridInfect.Core
{
    internal static class ClassicLevelData
    {
"""

FOOTER = """\
    }
}
"""


def main():
    with open(VECTORS) as f:
        data = json.load(f)
    levels = data["levels"]
    ids = sorted(int(k) for k in levels)
    if ids != list(range(128)):
        sys.exit(f"expected level ids 0..127, got {len(ids)} ids")

    boards, pieces, solutions = [], [], []
    for lid in ids:
        level = levels[str(lid)]
        board = level["board"]
        if len(board) != 66:
            sys.exit(f"level {lid}: board has {len(board)} cells")
        if any(v not in (0, 1, 2, 3, 5) for v in board):
            sys.exit(f"level {lid}: unexpected cell value in initial board")
        boards.append("".join(str(v) for v in board))
        if not 1 <= len(level["pieces"]) <= 8:
            sys.exit(f"level {lid}: {len(level['pieces'])} pieces")
        pieces.append(",".join(level["pieces"]))
        solutions.append(" ".join(f"{s['piece_index']}@{s['i'] * 6 + s['j']}" for s in level["solution"]))

    lines = [HEADER]
    lines.append("        internal static readonly string[] Boards =\n        {\n")
    for lid, b in zip(ids, boards):
        lines.append(f'            "{b}", // {lid}\n')
    lines.append("        };\n\n")
    lines.append("        internal static readonly string[] Pieces =\n        {\n")
    for lid, p in zip(ids, pieces):
        lines.append(f'            "{p}", // {lid}\n')
    lines.append("        };\n\n")
    lines.append("        internal static readonly string[] Solutions =\n        {\n")
    for lid, sol in zip(ids, solutions):
        lines.append(f'            "{sol}", // {lid}\n')
    lines.append("        };\n")
    lines.append(FOOTER)

    with open(OUTPUT, "w") as f:
        f.write("".join(lines))
    print(f"wrote {OUTPUT}: {len(ids)} levels")


if __name__ == "__main__":
    main()
