#!/usr/bin/env python3
"""Bake level pools into C# tables (EXECUTION_PLAN stage 3, and the Daily).

docs/worlds/*.jsonl -> unity/.../Levels/WorldData.g.cs   (the worlds, PLAY)
docs/daily/*.jsonl  -> unity/.../Levels/DailyData.g.cs   (one pool per weekday)

Each file starts with a header line {"world": {id, name, elements, seed,
spec}} followed by one gen_levels row per level. Levels are ordered by
grade, then deduction trace length, then effort, then seed (the curation
rule); pools are ordered by file name. Locks ("piece@cell") are the pieces
the loader places locked before play.

    python3 tools/bake_worlds.py
"""
import glob
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LEVELS = os.path.join(ROOT, "unity", "Assets", "_Project", "Core", "Levels")

HEADER = """// <auto-generated>
// Baked from docs/{source}/*.jsonl by tools/bake_worlds.py. Do not edit;
// regenerate. Pools in file order; levels per pool in curated order
// (grade, trace length, effort, seed). Boards are 66 chars row-major,
// values 0/1/2/3/5/6; solutions are "piece@cell" pairs in a winning order,
// locked pieces first; locks are the "piece@cell" pairs the loader places
// locked before play.
// </auto-generated>
namespace GridInfect.Core
{{
    internal static class {cls}
    {{
"""
FOOTER = """    }
}
"""


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def bake(source, cls, lo, hi):
    files = sorted(glob.glob(os.path.join(ROOT, "docs", source, "*.jsonl")))
    if not files:
        sys.exit(f"no level files under docs/{source}")
    pools = []
    for path in files:
        with open(path) as f:
            lines = [l for l in f.read().splitlines() if l.strip()]
        head = json.loads(lines[0])
        if "world" not in head:
            sys.exit(f"{path}: first line must be the pool header")
        w = head["world"]
        levels = [json.loads(l) for l in lines[1:]]
        if not lo <= len(levels) <= hi:
            sys.exit(f"{path}: {len(levels)} levels, want {lo}..{hi}")
        levels.sort(key=lambda r: (int(r["grade"][1]), len(r["trace"]), r["effort"], r["seed"]))
        hashes = set()
        for r in levels:
            if len(r["board"]) != 66 or any(c not in "012356" for c in r["board"]):
                sys.exit(f"{path}: bad board for seed {r['seed']}")
            if r["hash"] in hashes:
                sys.exit(f"{path}: duplicate level hash {r['hash']}")
            hashes.add(r["hash"])
        pools.append((w, levels))

    out = [HEADER.format(source=source, cls=cls)]
    out.append("        internal static readonly string[] Ids =\n        {\n")
    for w, _ in pools:
        out.append(f'            "{esc(w["id"])}",\n')
    out.append("        };\n\n        internal static readonly string[] Names =\n        {\n")
    for w, _ in pools:
        out.append(f'            "{esc(w["name"])}",\n')
    out.append("        };\n\n        internal static readonly string[] Elements =\n        {\n")
    for w, _ in pools:
        out.append(f'            "{esc(",".join(w.get("elements", [])))}",\n')
    out.append("        };\n\n        // Start of each pool in the flat level arrays; the last entry is the total.\n")
    out.append("        internal static readonly int[] Offsets =\n        {\n")
    offset = 0
    for _, levels in pools:
        out.append(f"            {offset},\n")
        offset += len(levels)
    out.append(f"            {offset},\n        }};\n\n")

    def array(name, ctype, values):
        out.append(f"        internal static readonly {ctype}[] {name} =\n        {{\n")
        for v in values:
            out.append(f"            {v},\n")
        out.append("        };\n\n")

    rows = [(w, r) for w, levels in pools for r in levels]
    array("Boards", "string", [f'"{r["board"]}"' for _, r in rows])
    array("Pieces", "string", [f'"{r["pieces"]}"' for _, r in rows])
    array("Solutions", "string",
          ['"' + " ".join(f"{p}@{c}" for p, c in r["solution"]) + '"' for _, r in rows])
    array("Grades", "int", [int(r["grade"][1]) for _, r in rows])
    array("Efforts", "int", [r["effort"] for _, r in rows])
    array("TraceLengths", "int", [len(r["trace"]) for _, r in rows])
    array("Seeds", "ulong", [f'{r["seed"]}ul' for _, r in rows])
    array("Hashes", "string", [f'"{r["hash"]}"' for _, r in rows])
    array("Reviewed", "bool", ["true" if r.get("reviewed") else "false" for _, r in rows])
    array("Relays", "string", ['"' + " ".join(f"{loc}:{arms}" for loc, arms in r.get("relays", [])) + '"' for _, r in rows])
    array("Locks", "string", ['"' + " ".join(f"{p}@{c}" for p, c in r.get("locks", [])) + '"' for _, r in rows])
    out.append(FOOTER)
    output = os.path.join(LEVELS, cls + ".g.cs")
    with open(output, "w") as f:
        f.write("".join(out))
    print(f"wrote {output}: {len(pools)} pools, {offset} levels")


def main():
    bake("worlds", "WorldData", 20, 25)
    bake("daily", "DailyData", 20, 60)


if __name__ == "__main__":
    main()
