#!/usr/bin/env python3
"""Bake docs/worlds/*.jsonl into WorldData.g.cs (EXECUTION_PLAN stage 3).

Each world file starts with a header line {"world": {id, name, elements,
seed, flags}} followed by one gen_levels row per level. Levels are ordered
by grade, then deduction trace length, then effort, then seed (the
curation rule), and the first/last two of every world carry reviewed=true
only when the row says so. Worlds are ordered by file name.

    python3 tools/bake_worlds.py
"""
import glob
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INPUT = os.path.join(ROOT, "docs", "worlds")
OUTPUT = os.path.join(ROOT, "unity", "Assets", "_Project", "Core", "Levels", "WorldData.g.cs")

HEADER = """// <auto-generated>
// Baked from docs/worlds/*.jsonl by tools/bake_worlds.py. Do not edit;
// regenerate. Worlds in file order; levels per world in curated order
// (grade, trace length, effort, seed). Boards are 66 chars row-major,
// values 0/1/2/3/5; solutions are "piece@cell" pairs in a winning order.
// </auto-generated>
namespace GridInfect.Core
{
    internal static class WorldData
    {
"""
FOOTER = """    }
}
"""


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    files = sorted(glob.glob(os.path.join(INPUT, "*.jsonl")))
    if not files:
        sys.exit("no world files under docs/worlds")
    worlds = []
    for path in files:
        with open(path) as f:
            lines = [l for l in f.read().splitlines() if l.strip()]
        head = json.loads(lines[0])
        if "world" not in head:
            sys.exit(f"{path}: first line must be the world header")
        w = head["world"]
        levels = [json.loads(l) for l in lines[1:]]
        if not 20 <= len(levels) <= 25:
            sys.exit(f"{path}: {len(levels)} levels, want 20..25")
        levels.sort(key=lambda r: (int(r["grade"][1]), len(r["trace"]), r["effort"], r["seed"]))
        hashes = set()
        for r in levels:
            if len(r["board"]) != 66 or any(c not in "01235" for c in r["board"]):
                sys.exit(f"{path}: bad board for seed {r['seed']}")
            if r["hash"] in hashes:
                sys.exit(f"{path}: duplicate level hash {r['hash']}")
            hashes.add(r["hash"])
        worlds.append((w, levels))

    out = [HEADER]
    out.append("        internal static readonly string[] Ids =\n        {\n")
    for w, _ in worlds:
        out.append(f'            "{esc(w["id"])}",\n')
    out.append("        };\n\n        internal static readonly string[] Names =\n        {\n")
    for w, _ in worlds:
        out.append(f'            "{esc(w["name"])}",\n')
    out.append("        };\n\n        internal static readonly string[] Elements =\n        {\n")
    for w, _ in worlds:
        out.append(f'            "{esc(",".join(w.get("elements", [])))}",\n')
    out.append("        };\n\n        // Start of each world in the flat level arrays; the last entry is the total.\n")
    out.append("        internal static readonly int[] Offsets =\n        {\n")
    offset = 0
    for _, levels in worlds:
        out.append(f"            {offset},\n")
        offset += len(levels)
    out.append(f"            {offset},\n        }};\n\n")

    def array(name, ctype, values, comment=None):
        out.append(f"        internal static readonly {ctype}[] {name} =\n        {{\n")
        for v in values:
            out.append(f"            {v},\n")
        out.append("        };\n\n")

    rows = [(w, r) for w, levels in worlds for r in levels]
    array("Boards", "string", [f'"{r["board"]}"' for _, r in rows])
    array("Pieces", "string", [f'"{r["pieces"]}"' for _, r in rows])
    array("Solutions", "string",
          ['"' + " ".join(f"{p}@{c}" for p, c in r["solution"]) + '"' for _, r in rows])
    array("Grades", "int", [int(r["grade"][1]) for _, r in rows])
    array("Efforts", "int", [r["effort"] for _, r in rows])
    array("TraceLengths", "int", [len(r["trace"]) for _, r in rows])
    array("Seeds", "ulong", [f'{r["seed"]}ul' for _, r in rows])
    array("Hashes", "string", [f'"{r["hash"]}"' for _, r in rows])
    array("Reviewed", "bool", ["true" if r.get("reviewed") else "false" for _, r in rows])
    array("Relays", "string", ['"' + " ".join(f"{loc}:{arms}" for loc, arms in r.get("relays", [])) + '"' for _, r in rows])
    out.append(FOOTER)
    with open(OUTPUT, "w") as f:
        f.write("".join(out))
    print(f"wrote {OUTPUT}: {len(worlds)} worlds, {offset} levels")


if __name__ == "__main__":
    main()
