#!/usr/bin/env python3
"""Emit unity/Assets/_Project/Game/View/SelectorGlyphs.g.cs: one drawn
glyph per non-Latin language, for the language selector's chip
(ARCHITECTURE.md §8). A reader who cannot read the Latin tag on the
chip reads the mark: 日 for Japanese, Я for Russian. Outlines, not text, so
the picker needs no font for a script it is offering — the same trick
LogoGlyphs.g.cs plays for the wordmark, in the same units (1/1000 em,
y down, baseline 0, quadratics and cubics flattened at eight steps).

The source faces are Noto (OFL) and are not in the repo — they are
megabytes each and only this script reads them. Point --fonts at a folder
holding them (google/fonts, ofl/<family>/):

    NotoSans.ttf  NotoSansJP.ttf  NotoSansKR.ttf  NotoSansSC.ttf
    NotoSansTC.ttf  NotoNaskhArabic.ttf  NotoSansHebrew.ttf

Usage: python3 tools/gen_selector_glyphs.py --fonts <dir>
"""

import argparse
import sys
from pathlib import Path

from fontTools.pens.basePen import BasePen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "unity" / "Assets" / "_Project" / "Game" / "View" / "SelectorGlyphs.g.cs"

# tag -> (the mark, the face it is drawn from). A script's own letterform,
# not a flag (ARCHITECTURE.md §8): a flag names a country.
MARKS = {
    "ru": ("Я", "NotoSans.ttf"),
    "ja": ("日", "NotoSansJP.ttf"),
    "ko": ("한", "NotoSansKR.ttf"),
    "zh-Hans": ("简", "NotoSansSC.ttf"),
    "zh-Hant": ("繁", "NotoSansTC.ttf"),
    "ar": ("ع", "NotoNaskhArabic.ttf"),
    "he": ("א", "NotoSansHebrew.ttf"),
}
STEPS = 8


class FlattenPen(BasePen):
    """Contours as flat [x0, y0, x1, y1, ...] lists in 1/1000 em, y down."""

    def __init__(self, glyph_set, k):
        super().__init__(glyph_set)
        self.k = k
        self.contours = []
        self._cur = None

    def _pt(self, p):
        return (p[0] * self.k, -p[1] * self.k)

    def _moveTo(self, p):
        self._cur = list(self._pt(p))

    def _lineTo(self, p):
        self._cur.extend(self._pt(p))

    def _qCurveToOne(self, c, p):
        x0, y0 = self._cur[-2], self._cur[-1]
        cx, cy = self._pt(c)
        x1, y1 = self._pt(p)
        for i in range(1, STEPS + 1):
            t = i / STEPS
            u = 1 - t
            self._cur.extend((u * u * x0 + 2 * u * t * cx + t * t * x1,
                              u * u * y0 + 2 * u * t * cy + t * t * y1))

    def _curveToOne(self, c1, c2, p):
        x0, y0 = self._cur[-2], self._cur[-1]
        ax, ay = self._pt(c1)
        bx, by = self._pt(c2)
        x1, y1 = self._pt(p)
        for i in range(1, STEPS + 1):
            t = i / STEPS
            u = 1 - t
            self._cur.extend((u ** 3 * x0 + 3 * u * u * t * ax + 3 * u * t * t * bx + t ** 3 * x1,
                              u ** 3 * y0 + 3 * u * u * t * ay + 3 * u * t * t * by + t ** 3 * y1))

    def _closePath(self):
        if self._cur and len(self._cur) >= 6:
            # Drop a closing point that repeats the start; the rasteriser closes.
            if abs(self._cur[0] - self._cur[-2]) < 1e-6 and abs(self._cur[1] - self._cur[-1]) < 1e-6:
                self._cur = self._cur[:-2]
            self.contours.append(self._cur)
        self._cur = None

    def _endPath(self):
        self._closePath()


def outline(font_path, ch):
    font = TTFont(font_path)
    cmap = font.getBestCmap()
    name = cmap.get(ord(ch))
    if name is None:
        sys.exit(f"gen_selector_glyphs: {font_path.name} has no glyph for {ch!r}")
    glyph_set = font.getGlyphSet()
    pen = FlattenPen(glyph_set, 1000.0 / font["head"].unitsPerEm)
    glyph_set[name].draw(pen)
    return pen.contours, glyph_set[name].width * 1000.0 / font["head"].unitsPerEm


def fmt(v):
    return f"{v:.1f}f"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fonts", required=True, help="folder holding the Noto sources")
    args = ap.parse_args()
    fonts = Path(args.fonts)

    L = []
    add = L.append
    add("// <auto-generated> tools/gen_selector_glyphs.py. Do not edit; regenerate.")
    add("// The language selector's marks (ARCHITECTURE.md §8): one glyph of")
    add("// its own script per non-Latin language, as flattened outlines in")
    add("// 1/1000 em, y down, baseline 0, drawn from Noto (OFL). Outlines, not")
    add("// text: the picker needs no font for a script it offers.")
    add("namespace GridInfect.Game")
    add("{")
    add("    public static class SelectorGlyphs")
    add("    {")
    add("        public const float Em = 1000f;")
    add("")
    add("        // Null for a tag with no mark: the Latin ones, whose chip is the mark.")
    add("        public static float[][] Contours(string tag)")
    add("        {")
    add("            switch (tag)")
    add("            {")
    ids = {}
    for tag in MARKS:
        ident = "M_" + tag.replace("-", "_")
        ids[tag] = ident
        add(f"                case \"{tag}\": return {ident};")
    add("            }")
    add("            return null;")
    add("        }")
    for tag, (ch, file) in MARKS.items():
        contours, advance = outline(fonts / file, ch)
        add("")
        add(f"        // {tag}: {ch} ({file}), advance {advance:.0f}")
        add(f"        static readonly float[][] {ids[tag]} =")
        add("        {")
        for c in contours:
            add("            new float[] { " + ", ".join(fmt(v) for v in c) + " },")
        add("        };")
    add("    }")
    add("}")
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(MARKS)} marks)")


if __name__ == "__main__":
    main()
