// <auto-generated>
// Generated by tools/gen_undo_fixtures.py against the Python reference
// implementation (docs/tools/verify_test_vectors.py + a literal clearPiece
// port). Do not edit; re-run the script instead.
// Board strings: 66 chars row-major, '.' = void, digit = cell value.
// Script ops: P<piece>@<i>,<j> = place + resolve; C<piece> = clear (undo).
// </auto-generated>

namespace GridInfect.Core.Tests
{
    public static class UndoFixtures
    {
        public struct Scenario
        {
            public string Name;
            public string Board;
            public string Pieces;
            public string Script;
            public string ExpectedBoard;
            public int ExpectedRepelQueue;
            public int ExpectedPlacedMask;
            public bool ExpectedSolved;
            public int ExpectedSolvedEvents;
            public int ExpectedUnboundEvents;
        }

        public static readonly Scenario[] All =
        {
            new Scenario
            {
                Name = "single_undo_restores_board",
                Board = "..1.1...1.1...1.1...1.1...1.1...1.1...1.1...1.1...1.1...1.1...1.1.",
                Pieces = "UD",
                Script = "P0@5,2;C0",
                ExpectedBoard = "..1.1...1.1...1.1...1.1...1.1...1.1...1.1...1.1...1.1...1.1...1.1.",
                ExpectedRepelQueue = 0,
                ExpectedPlacedMask = 0,
                ExpectedSolved = false,
                ExpectedSolvedEvents = 0,
                ExpectedUnboundEvents = 0,
            },
            new Scenario
            {
                Name = "undo_keeps_other_pieces_coverage",
                Board = ".1...1.1...1.1...1.1...1.1...1111..1.1...1.1...1111111.1...1.1...1",
                Pieces = "UD,LR",
                Script = "P0@3,1;P1@8,3;C1",
                ExpectedBoard = ".4...1.4...1.4...1.4...1.4...1141..1.4...1.4...1141111.4...1.4...1",
                ExpectedRepelQueue = 0,
                ExpectedPlacedMask = 1,
                ExpectedSolved = false,
                ExpectedSolvedEvents = 0,
                ExpectedUnboundEvents = 0,
            },
            new Scenario
            {
                Name = "undo_accumulates_repel_queue",
                Board = "..3.1...1.1...1.1...1.1...1.1...1.1...1.1...1.1...1.1...1.1...1.1.",
                Pieces = "UD,U",
                Script = "P0@5,2;P1@7,2;C1",
                ExpectedBoard = "..3.1...1.1...1.1...1.1...1.1...4.1...4.1...4.1...4.1...4.1...4.1.",
                ExpectedRepelQueue = 2,
                ExpectedPlacedMask = 1,
                ExpectedSolved = false,
                ExpectedSolvedEvents = 0,
                ExpectedUnboundEvents = 0,
            },
            new Scenario
            {
                Name = "stale_trip_flag_full_resets_mid_undo",
                Board = "..1.....1.....1.....1.....1.....1.....1.....1.1...1.....1.....5...",
                Pieces = "D,R",
                Script = "P1@7,2;P0@0,2;C1",
                ExpectedBoard = "..1.....1.....1.....1.....1.....1.....1.....1.1...1.....1.....5...",
                ExpectedRepelQueue = 0,
                ExpectedPlacedMask = 0,
                ExpectedSolved = false,
                ExpectedSolvedEvents = 1,
                ExpectedUnboundEvents = 1,
            },
            new Scenario
            {
                Name = "repel_rerun_walks_over_wall_after_undo",
                Board = "..1.1...1.1...1.1...2.1...1.1...1.1...1.1...1.1...1.1...1.1...3.1.",
                Pieces = "UD,D",
                Script = "P0@1,2;P1@4,2;C1",
                ExpectedBoard = "..4.1...4.1...1.1...2.1...1.1...1.1...1.1...1.1...1.1...1.1...3.1.",
                ExpectedRepelQueue = 1,
                ExpectedPlacedMask = 1,
                ExpectedSolved = false,
                ExpectedSolvedEvents = 0,
                ExpectedUnboundEvents = 0,
            },
            new Scenario
            {
                Name = "mid_undo_win_check_ignores_99_marks",
                Board = "..1.....1.....1.....1.....1...1.1.....1.....1.....1.....1.....1...",
                Pieces = "UD,R",
                Script = "P0@4,2;P1@5,2;C1",
                ExpectedBoard = "..4.....4.....4.....4.....4...1.4.....4.....4.....4.....4.....4...",
                ExpectedRepelQueue = 0,
                ExpectedPlacedMask = 1,
                ExpectedSolved = true,
                ExpectedSolvedEvents = 1,
                ExpectedUnboundEvents = 0,
            },
        };
    }
}
