// <auto-generated>
// Generated by tools/gen_undo_fixtures.py against the Python reference
// implementation (docs/tools/verify_test_vectors.py + a literal clearPiece
// port). Do not edit; re-run the script instead.
// Board strings: 66 chars row-major, '.' = void, digit = cell value.
// Script ops: P<piece>@<i>,<j> = place + resolve; C<piece> = clear (undo).
// </auto-generated>

namespace GridInfect.Core.Tests
{
    public static class UndoFixtures
    {
        public struct Scenario
        {
            public string Name;
            public string Board;
            public string Pieces;
            public string Script;
            public string ExpectedBoard;
            public int ExpectedRepelQueue;
            public int ExpectedPlacedMask;
            public bool ExpectedSolved;
            public int ExpectedSolvedEvents;
            public int ExpectedUnboundEvents;
        }

        public static readonly Scenario[] All =
        {
            new Scenario
            {
                Name = "single_undo_restores_board",
                Board = "......................11111111111...........11111111111...........",
                Pieces = "LR",
                Script = "P0@2,5;C0",
                ExpectedBoard = "......................11111111111...........11111111111...........",
                ExpectedRepelQueue = 0,
                ExpectedPlacedMask = 0,
                ExpectedSolved = false,
                ExpectedSolvedEvents = 0,
                ExpectedUnboundEvents = 0,
            },
            new Scenario
            {
                Name = "undo_keeps_other_pieces_coverage",
                Board = ".....1..1..11111111111.....1..1..........1..........1..11111111111",
                Pieces = "LR,UD",
                Script = "P0@1,3;P1@3,8;C1",
                ExpectedBoard = ".....1..1..44444444444.....1..1..........1..........1..11111111111",
                ExpectedRepelQueue = 0,
                ExpectedPlacedMask = 1,
                ExpectedSolved = false,
                ExpectedSolvedEvents = 0,
                ExpectedUnboundEvents = 0,
            },
            new Scenario
            {
                Name = "undo_accumulates_repel_queue",
                Board = "......................31111111111...........11111111111...........",
                Pieces = "LR,L",
                Script = "P0@2,5;P1@2,7;C1",
                ExpectedBoard = "......................31111444444...........11111111111...........",
                ExpectedRepelQueue = 2,
                ExpectedPlacedMask = 1,
                ExpectedSolved = false,
                ExpectedSolvedEvents = 0,
                ExpectedUnboundEvents = 0,
            },
            new Scenario
            {
                Name = "stale_trip_flag_full_resets_mid_undo",
                Board = "......................11111111115..................1..............",
                Pieces = "R,D",
                Script = "P1@2,7;P0@2,0;C1",
                ExpectedBoard = "......................11111111115..................1..............",
                ExpectedRepelQueue = 0,
                ExpectedPlacedMask = 0,
                ExpectedSolved = false,
                ExpectedSolvedEvents = 1,
                ExpectedUnboundEvents = 1,
            },
            new Scenario
            {
                Name = "repel_rerun_walks_over_wall_after_undo",
                Board = "......................11121111113...........11111111111...........",
                Pieces = "LR,R",
                Script = "P0@2,1;P1@2,4;C1",
                ExpectedBoard = "......................44121111113...........11111111111...........",
                ExpectedRepelQueue = 1,
                ExpectedPlacedMask = 1,
                ExpectedSolved = false,
                ExpectedSolvedEvents = 0,
                ExpectedUnboundEvents = 0,
            },
            new Scenario
            {
                Name = "mid_undo_win_check_ignores_99_marks",
                Board = ".....1................11111111111.................................",
                Pieces = "LR,D",
                Script = "P0@2,4;P1@2,5;C1",
                ExpectedBoard = ".....1................44444444444.................................",
                ExpectedRepelQueue = 0,
                ExpectedPlacedMask = 1,
                ExpectedSolved = true,
                ExpectedSolvedEvents = 1,
                ExpectedUnboundEvents = 0,
            },
        };
    }
}
